@extends('layouts.app')
@section('content')
<div class="container"><section class="hero"><div class="hero-content"><span class="hero-badge">انتخاب هوشمندانه، خرید مطمئن</span><h1>{{ $banner?->title??'جدیدترین کالای دیجیتال با بهترین قیمت' }}</h1><p>{{ $banner?->subtitle??'از گوشی و لپ‌تاپ تا گجت‌های هوشمند؛ همه‌چیز یک‌جا' }}</p><a class="btn" href="{{ $banner?->url??route('products') }}">مشاهده و خرید <x-icon name="chevron"/></a></div><div class="hero-visual"><div class="hero-products"><img src="/images/products/galaxy-s24.webp" alt="گوشی"><img src="/images/products/macbook.webp" alt="لپ تاپ"><img src="/images/products/apple-watch.webp" alt="ساعت"></div><div class="hero-dots"><i></i><i></i><i></i></div></div></section>
<div class="benefits"><div class="benefit"><x-icon name="headset"/><span><strong>پشتیبانی ۲۴/۷</strong><small>هر زمان کنار شما هستیم</small></span></div><div class="benefit"><x-icon name="truck"/><span><strong>ارسال سریع</strong><small>تحویل فوری در سراسر کشور</small></span></div><div class="benefit"><x-icon name="shield"/><span><strong>۷ روز ضمانت بازگشت</strong><small>خرید آسوده و مطمئن</small></span></div><div class="benefit"><x-icon name="check"/><span><strong>ضمانت اصالت کالا</strong><small>تضمین کالای اصل</small></span></div></div>
<section class="section"><div class="section-title"><h2>دسته‌بندی‌های محبوب</h2><a href="/products">مشاهده همه</a></div><div class="category-row">@foreach($categories as $category)<a class="category-card" href="{{ route('category',$category) }}"><span class="category-icon"><x-icon name="box"/></span><strong>{{ $category->name }}</strong></a>@endforeach</div></section>
<section class="section"><div class="section-title"><h2>پیشنهادهای ویژه</h2><a href="/products">مشاهده همه</a></div><div class="products-grid home-products">@foreach($featured as $product)@include('shop._product-card')@endforeach</div></section>
<section class="section promo-grid"><div class="promo"><div><span>فروش ویژه</span><h3>ساعت‌های هوشمند</h3><p>تا <b>۲۵٪ تخفیف</b></p><a class="btn btn-sm" href="/category/watch">مشاهده محصولات</a></div><img src="/images/products/apple-watch.webp" alt="ساعت هوشمند"></div><div class="promo"><div><span>تخفیف ویژه</span><h3>انواع هدفون و هندزفری</h3><p>تا <b>۳۰٪ تخفیف</b></p><a class="btn btn-sm" href="/category/audio">مشاهده محصولات</a></div><img src="/images/products/sony-headphone.webp" alt="هدفون"></div></section>
<section class="section"><div class="section-title"><h2>پرفروش‌ترین محصولات</h2><a href="/products?sort=popular">مشاهده همه</a></div><div class="products-grid home-products">@foreach($latest as $product)@include('shop._product-card')@endforeach</div></section>
<section class="section"><div class="section-title"><h2>برندهای محبوب</h2></div><div class="brands">@foreach(['Apple','SAMSUNG','SONY','ASUS','hp','Lenovo','JBL','Canon'] as $brand)<div class="brand-box">{{ $brand }}</div>@endforeach</div></section>
<section class="section"><div class="section-title"><h2>مجله دیجینو</h2><a href="/about">مشاهده همه</a></div><div class="articles">@foreach([['راهنمای خرید گوشی هوشمند در سال ۱۴۰۵','مقایسه مشخصات و نکاتی که پیش از انتخاب موبایل باید بدانید.'],['بهترین لپ‌تاپ‌ها برای دانشجویان','مدل‌های مناسب برنامه‌نویسی، طراحی و کارهای روزمره را بشناسید.'],['مقایسه ایرپاد پرو ۲ و رقبا','کیفیت صدا، حذف نویز و شارژدهی محبوب‌ترین هدفون‌ها.']] as $a)<article class="article"><div class="article-cover"><x-icon name="box"/></div><div class="article-content"><h3>{{ $a[0] }}</h3><p>{{ $a[1] }}</p></div></article>@endforeach</div></section></div>
@endsection