@extends('layouts.admin')
@section('title',$title.' | مدیریت دیجینو')@section('heading',$title)
@section('content')<div class="admin-tools"><div><h2>{{ $title }}</h2><p style="color:#7a838d">مدیریت و مشاهده اطلاعات ثبت‌شده</p></div>@if($type==='products')<a class="btn" href="{{ route('admin.products.create') }}"><x-icon name="plus"/> افزودن محصول</a>@elseif(in_array($type,['categories','coupons','banners']))<button class="btn" data-open="add-modal"><x-icon name="plus"/> افزودن جدید</button>@endif</div>
@if($type==='settings')<form class="admin-form ajax-form" action="{{ route('admin.settings.update') }}" method="post"><input type="hidden" name="_method" value="PATCH"><div class="form-grid"><label class="field"><span>نام فروشگاه</span><input name="store_name" value="{{ DB::table('settings')->where('key','store_name')->value('value')??'دیجینو' }}"></label><label class="field"><span>تلفن پشتیبانی</span><input name="support_phone" value="{{ DB::table('settings')->where('key','support_phone')->value('value')??'۰۲۱-۱۲۳۴۵۶۷۸' }}"></label><label class="field"><span>ایمیل</span><input type="email" name="support_email" value="{{ DB::table('settings')->where('key','support_email')->value('value')??'info@digino.ir' }}"></label><label class="field"><span>هزینه ارسال (تومان)</span><input type="number" name="shipping_cost" value="{{ DB::table('settings')->where('key','shipping_cost')->value('value')??150000 }}"></label><label class="field full"><span>توضیح کوتاه</span><textarea name="store_description">{{ DB::table('settings')->where('key','store_description')->value('value')??'فروشگاه هوشمند کالای دیجیتال' }}</textarea></label></div><button class="btn" style="margin-top:18px">ذخیره تنظیمات</button></form>@else
<section class="admin-card"><table class="admin-table"><thead><tr>@if($type==='products')<th>محصول</th><th>دسته</th><th>قیمت</th><th>موجودی</th><th>وضعیت</th>@elseif($type==='categories')<th>نام</th><th>شناسه</th><th>تعداد محصول</th><th>وضعیت</th>@elseif($type==='orders')<th>شماره</th><th>کاربر</th><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th>@elseif($type==='customers')<th>مشتری</th><th>ایمیل</th><th>موبایل</th><th>تاریخ عضویت</th>@elseif($type==='coupons')<th>کد</th><th>نوع</th><th>مقدار</th><th>مصرف</th><th>انقضا</th>@elseif($type==='reviews')<th>کاربر</th><th>محصول</th><th>امتیاز</th><th>دیدگاه</th><th>تأیید</th>@elseif($type==='inventory')<th>محصول</th><th>SKU</th><th>موجودی</th><th>وضعیت</th><th>ویرایش سریع</th>@elseif($type==='banners')<th>عنوان</th><th>جایگاه</th><th>لینک</th><th>ترتیب</th><th>وضعیت</th>@endif<th>عملیات</th></tr></thead><tbody>
@foreach($items as $item)<tr>@if($type==='products')<td><div class="admin-product"><img src="/{{ $item->image }}"><span>{{ Str::limit($item->name,35) }}</span></div></td><td>{{ $item->category->name }}</td><td>{{ number_format($item->price) }}</td><td>{{ $item->stock }}</td><td><span class="status {{ $item->is_active?'status-delivered':'status-cancelled' }}">{{ $item->is_active?'فعال':'غیرفعال' }}</span></td>
@elseif($type==='categories')<td><b>{{ $item->name }}</b></td><td>{{ $item->slug }}</td><td>{{ $item->products_count }}</td><td><span class="status status-delivered">فعال</span></td>
@elseif($type==='orders')<td><b>{{ $item->number }}</b></td><td>{{ $item->user->name }}</td><td>{{ number_format($item->total) }}</td><td><span class="status status-{{ $item->status }}">{{ $item->status }}</span></td><td>{{ $item->created_at->format('Y/m/d') }}</td>
@elseif($type==='customers')<td><b>{{ $item->name }}</b></td><td>{{ $item->email }}</td><td>{{ $item->phone??'-' }}</td><td>{{ $item->created_at->format('Y/m/d') }}</td>
@elseif($type==='coupons')<td><b>{{ $item->code }}</b></td><td>{{ $item->type==='percent'?'درصدی':'مبلغ ثابت' }}</td><td>{{ number_format($item->value) }}</td><td>{{ $item->used_count }}/{{ $item->usage_limit??'∞' }}</td><td>{{ $item->expires_at??'-' }}</td>
@elseif($type==='reviews')<td>{{ $item->user->name }}</td><td>{{ Str::limit($item->product->name,25) }}</td><td>⭐ {{ $item->rating }}</td><td>{{ Str::limit($item->body,45) }}</td><td><span class="status {{ $item->is_approved?'status-delivered':'status-processing' }}">{{ $item->is_approved?'تأییدشده':'در انتظار' }}</span></td>
@elseif($type==='inventory')<td><div class="admin-product"><img src="/{{ $item->image }}"><span>{{ Str::limit($item->name,30) }}</span></div></td><td>{{ $item->sku }}</td><td><b>{{ $item->stock }}</b></td><td><span class="status {{ $item->stock<10?'status-cancelled':'status-delivered' }}">{{ $item->stock<10?'رو به اتمام':'موجود' }}</span></td><td><form class="ajax-form" action="{{ route('admin.resource.action',['inventory',$item->id]) }}" method="post" style="display:flex;gap:5px"><input type="hidden" name="_method" value="PATCH"><input name="stock" value="{{ $item->stock }}" style="width:65px;border:1px solid #ddd;border-radius:6px;padding:5px"><button class="btn btn-sm">ثبت</button></form></td>
@elseif($type==='banners')<td><b>{{ $item->title }}</b></td><td>{{ $item->position }}</td><td>{{ $item->url }}</td><td>{{ $item->sort_order }}</td><td><span class="status status-delivered">فعال</span></td>@endif
<td><div class="table-actions">@if($type==='products')<a class="icon-btn" href="{{ route('admin.products.edit',$item) }}"><x-icon name="edit"/></a><button class="icon-btn" data-delete="{{ route('admin.products.delete',$item) }}"><x-icon name="trash"/></button>@elseif($type==='orders')<a class="icon-btn" href="{{ route('admin.orders.show',$item) }}"><x-icon name="chevron"/></a>@elseif($type==='reviews' && !$item->is_approved)<form class="ajax-form" action="{{ route('admin.resource.action',['reviews',$item->id]) }}"><input type="hidden" name="_method" value="PATCH"><input type="hidden" name="approved" value="1"><button class="btn btn-sm">تأیید</button></form>@else<span style="color:#9aa2a9">—</span>@endif</div></td></tr>@endforeach</tbody></table>@if(method_exists($items,'links'))<div class="pagination">@foreach(range(1,$items->lastPage()) as $p)<a class="{{ $items->currentPage()===$p?'active':'' }}" href="{{ $items->url($p) }}">{{ $p }}</a>@endforeach</div>@endif</section>@endif
@if(in_array($type,['categories','coupons','banners']))<div class="modal" id="add-modal"><form class="modal-card ajax-form" action="{{ route('admin.resource.store',$type) }}" method="post"><button type="button" data-close class="modal-x"><x-icon name="close"/></button><h3>افزودن {{ $title }}</h3>@if($type==='categories')<label class="field"><span>نام دسته‌بندی</span><input name="name" required></label><label class="field"><span>توضیحات</span><textarea name="description"></textarea></label>@elseif($type==='coupons')<label class="field"><span>کد تخفیف</span><input name="code" required></label><label class="field"><span>نوع</span><select name="type"><option value="percent">درصدی</option><option value="fixed">ثابت</option></select></label><label class="field"><span>مقدار</span><input name="value" type="number" required></label><label class="field"><span>حداقل سفارش</span><input name="min_order" type="number" value="0"></label>@else<label class="field"><span>عنوان</span><input name="title" required></label><label class="field"><span>زیرعنوان</span><input name="subtitle"></label><label class="field"><span>لینک</span><input name="url" value="/products"></label><input type="hidden" name="position" value="home">@endif<button class="btn btn-block" style="margin-top:18px">ذخیره</button></form></div>@endif@endsection