@extends('layouts.app')
@section('content')
<div class="container home-page"><section class="hero" aria-label="پیشنهادهای دیجینو"><div class="hero-copy"><span class="eyebrow"><i></i> دنیای دیجیتال، نزدیک‌تر از همیشه</span><h1>جدیدترین‌های دیجیتال،<br><span>هوشمندانه</span> انتخاب کن.</h1><p>از اولین انتخاب تا لحظهٔ روشن‌کردن؛<br>بهترین همراه‌های دیجیتال، اینجا منتظر تو هستند.</p><a href="/products" class="btn btn-primary hero-cta">کشف و خرید محصولات @include('partials.icon',['name'=>'arrow'])</a><span class="hero-footnote">انتخاب‌های تازه، تجربه‌ای متفاوت</span></div><div class="hero-art"><div class="hero-ring ring-one"></div><div class="hero-ring ring-two"></div><div class="hero-platform"></div><img class="hero-laptop" src="/assets/images/laptop.jpg" alt="لپ‌تاپ مک‌بوک ایر M2"><img class="hero-phone" src="/assets/images/iphone.jpg" alt="آیفون ۱۵ پرو مکس"><img class="hero-headphones" src="/assets/images/headphones.jpg" alt="هدفون بی‌سیم سونی"><span class="hero-art-label"><span class="tiny-dot"></span> تکنولوژی، برای زندگی بهتر</span><span class="hero-spark spark-one">+</span><span class="hero-spark spark-two">+</span></div><div class="hero-pagination"><button class="active" data-hero-slide="0" aria-label="پیشنهاد کالای دیجیتال" aria-pressed="true"></button><button data-hero-slide="1" aria-label="پیشنهاد محصولات صوتی" aria-pressed="false"></button><button data-hero-slide="2" aria-label="پیشنهاد ساعت هوشمند" aria-pressed="false"></button></div></section>
@include('partials.services')
<section class="section categories-section"><div class="section-heading"><div><span class="section-kicker">برای هر نیاز، یک انتخاب</span><h2>دسته‌بندی‌های محبوب</h2></div><a href="/categories" class="view-all">مشاهده همه @include('partials.icon',['name'=>'left'])</a></div><div class="category-row">@foreach($navCategories as $c)<a class="category-card" href="/category/{{ $c->slug }}"><div><img src="{{ $c->image }}" alt="" loading="lazy" width="100" height="85"></div><h3>{{ $c->name }}</h3></a>@endforeach</div></section>
<section class="section offers-section"><div class="section-heading"><div class="heading-inline"><div class="heading-icon">@include('partials.icon',['name'=>'ticket'])</div><div><span class="section-kicker">فرصت یک خرید هوشمندانه</span><h2>پیشنهادهای <span class="text-brand">ویژه</span></h2></div></div><a href="/products?sale=1" class="view-all">همه پیشنهادها @include('partials.icon',['name'=>'left'])</a></div><div class="products-row">@foreach($featured as $p)@include('partials.product-card')@endforeach</div></section>
<div class="promo-grid">@forelse($banners->take(2) as $banner)<a class="promo-banner" href="{{ $banner->link }}" style="--promo-bg:{{ $banner->color }}"><div><span>{{ $loop->first?'ریتم زندگی، در دستان تو':'فقط تو و صدای مورد علاقه‌ات' }}</span><h2>{{ $banner->title }}</h2><p>{{ $banner->subtitle }}</p><b>مشاهده محصولات @include('partials.icon',['name'=>'arrow'])</b></div><img src="{{ $banner->image }}" alt="{{ $banner->title }}" loading="lazy"></a>@empty @endforelse</div>
<section class="section"><div class="section-heading"><div><span class="section-kicker">انتخاب بعدی تو، شاید اینجاست</span><h2>محصولات منتخب دیجینو</h2></div><a href="/products?sort=popular" class="view-all">مشاهده همه @include('partials.icon',['name'=>'left'])</a></div><div class="products-row">@foreach($popular as $p)@include('partials.product-card')@endforeach</div></section>
<section class="section brands-section"><div class="section-heading"><div><span class="section-kicker">نام‌هایی که می‌شناسید</span><h2>برندهای محبوب</h2></div><a href="/products" class="view-all">همه برندها @include('partials.icon',['name'=>'left'])</a></div><div class="brands-row">@foreach(['Apple','Samsung','JBL','Sony','ASUS','Anker','Logitech','Canon'] as $brand)<a href="/products?brand[]={{ $brand }}" class="brand-tile brand-{{ strtolower($brand) }}">@if($brand==='Apple')<svg viewBox="0 0 24 24" width="34" height="38" fill="currentColor" aria-label="اپل"><path d="M17.4 12.7c0-2 1.6-3.1 1.7-3.2-1-1.5-2.7-1.7-3.3-1.7-1.4-.2-2.7.8-3.4.8-.7 0-1.8-.8-3-.8-1.6 0-3.1 1-4 2.4-1.7 3-.5 7.6 1.2 10 .8 1.2 1.8 2.5 3 2.4 1.2 0 1.7-.8 3.2-.8 1.5 0 2 .8 3.3.8 1.4 0 2.2-1.2 3-2.4 1-1.4 1.4-2.8 1.4-2.9-.1 0-3.1-1.2-3.1-4.6ZM15.2 6.2c.7-.9 1.2-2 1.1-3.2-1.1 0-2.4.7-3.2 1.6-.6.7-1.2 1.9-1.1 3 1.2.1 2.5-.6 3.2-1.4Z"/></svg>@elseif($brand==='Microsoft')<span class="microsoft-mark"><i></i><i></i><i></i><i></i></span>@else{{ $brand }}@endif</a>@endforeach</div></section>
<section class="section journal-section"><div class="section-heading"><div><span class="section-kicker">بخوان، مقایسه کن، بهتر انتخاب کن</span><h2>مجله دیجینو</h2></div><a href="/journal" class="view-all">مطالب بیشتر @include('partials.icon',['name'=>'left'])</a></div><div class="journal-grid">@foreach($articles as $article)<a class="journal-card" href="/journal/{{ $article->slug }}"><div class="journal-image"><img src="{{ $article->image }}" alt="{{ $article->title }}" loading="lazy"><span>راهنمای خرید</span></div><div class="journal-copy"><h3>{{ $article->title }}</h3><p>{{ $article->excerpt }}</p><div><span>راهنمای انتخاب</span><span>ادامه مطلب @include('partials.icon',['name'=>'arrow'])</span></div></div></a>@endforeach</div></section>
</div>
@endsection
