<?php

return [
    'required' => 'وارد کردن :attribute الزامی است.', 'email' => 'فرمت :attribute معتبر نیست.', 'unique' => ':attribute قبلاً ثبت شده است.', 'confirmed' => 'تکرار :attribute مطابقت ندارد.', 'accepted' => 'پذیرش :attribute الزامی است.', 'integer' => ':attribute باید عدد صحیح باشد.', 'numeric' => ':attribute باید عدد باشد.', 'string' => ':attribute باید متن باشد.', 'regex' => 'فرمت :attribute معتبر نیست.', 'in' => 'مقدار :attribute مجاز نیست.', 'exists' => ':attribute انتخاب‌شده معتبر نیست.', 'current_password' => 'رمز عبور فعلی صحیح نیست.', 'image' => ':attribute باید یک تصویر معتبر باشد.', 'mimes' => 'فرمت :attribute باید یکی از :values باشد.', 'date' => ':attribute باید تاریخ معتبر باشد.', 'json' => 'ساختار :attribute باید JSON معتبر باشد.', 'alpha_dash' => ':attribute فقط می‌تواند شامل حروف، اعداد، خط تیره و زیرخط باشد.', 'uuid' => 'شناسه درخواست معتبر نیست.', 'boolean' => 'مقدار :attribute معتبر نیست.', 'dimensions' => 'ابعاد تصویر بیش از حد مجاز است.',
    'min' => ['string' => ':attribute باید حداقل :min کاراکتر باشد.', 'numeric' => ':attribute نباید کمتر از :min باشد.', 'file' => 'حجم :attribute باید حداقل :min کیلوبایت باشد.'],
    'max' => ['string' => ':attribute نباید بیشتر از :max کاراکتر باشد.', 'numeric' => ':attribute نباید بیشتر از :max باشد.', 'file' => 'حجم :attribute نباید بیشتر از :max کیلوبایت باشد.'],
    'between' => ['numeric' => ':attribute باید بین :min و :max باشد.'], 'gte' => ['numeric' => ':attribute نباید از :value کمتر باشد.'],
    'password' => ['letters' => ':attribute باید حداقل یک حرف داشته باشد.', 'numbers' => ':attribute باید حداقل یک عدد داشته باشد.'],
    'attributes' => ['name' => 'نام', 'email' => 'ایمیل', 'password' => 'رمز عبور', 'current_password' => 'رمز فعلی', 'phone' => 'شماره موبایل', 'terms' => 'شرایط استفاده', 'city' => 'شهر', 'postal_code' => 'کد پستی', 'address' => 'آدرس', 'quantity' => 'تعداد', 'code' => 'کد تخفیف', 'body' => 'متن', 'rating' => 'امتیاز', 'subject' => 'موضوع', 'price' => 'قیمت', 'old_price' => 'قیمت پیشین', 'stock' => 'موجودی', 'image' => 'تصویر', 'slug' => 'شناسه انگلیسی', 'sku' => 'کد محصول', 'brand' => 'برند', 'category_id' => 'دسته‌بندی', 'color' => 'رنگ', 'description' => 'توضیحات', 'percent' => 'درصد تخفیف', 'expires_at' => 'تاریخ انقضا', 'reply' => 'پاسخ', 'status' => 'وضعیت', 'title' => 'عنوان', 'subtitle' => 'زیرعنوان', 'link' => 'پیوند', 'specs_json' => 'مشخصات فنی', 'address_id' => 'آدرس تحویل'],
];
